@server = https://special-garbanzo-pv5vqw547p73795x-8082.app.github.dev

###
GET {{server}}/api/productos
###
POST {{server}}/api/productos
Content-Type: application/json

{"nombre": "Aceite" }


###
GET {{server}}/api/ventas

###
GET {{server}}/api/ventas/1
###
GET {{server}}/api/ventas/1/formacion
###
GET {{server}}/api/ventadetalles



